### ISSUE TITLE
make latexpdf throws error

### ISSUE THREAD

**Issue by fabianmoss** [sphinx-notes/lilypond#11]
Is it possible to include Lilypond output in a PDF generated by Sphinx? 

I have the following code in one of my `.rst` files

```
.. lily::
   :noedge:
   :nofooter:
   :audio:

   \version "2.20.0"
   \header {
   }
   \score {
   <<
      \new Staff \relative c' {
      \tempo 4 = 120
         c4 cis d ees e f fis g aes a bes b
   }
   >>
   }
```
and get the error `raise NotImplementedError(NotImplementedError: <class 'sphinx.writers.latex.LaTeXTranslator'> departing unknown node type: lily_outline_nod`. Is LaTeX conversion really not implemented yet or am I missing something?

**Comment by SilverRainZ** [comment]
LaTeX is not supported for now because I know very little about it.

**Comment by fabianmoss** [comment]
Thanks for the quick answer and for this great contrib. Maybe this can be added in the future...

**Comment by SilverRainZ** [comment]
I will try to implement it in few weeks, just keep this issue opening

**Comment by SilverRainZ** [comment]
Hello @fabianmoss, I just added a basic LaTeX support for this extension, can you please have a try? You can clone this branch and run `make install` to get it installed.

**Comment by SilverRainZ** [comment]
sphinxnotes-lilypond==1.5 lands this changes.
