### ISSUE TITLE
SVGs cropping right and bottom

### ISSUE THREAD

**Issue by kjcole** [sphinx-notes/lilypond#15]
Since large PNGs were giving me trouble, I decided to switch the configuration to SVGs.

However, this crops the right and bottom of the score, eliminating too much.

The result can be seen by looking at any of the 47 scores (so far) at:

https://ubuntourist.codeberg.page/Celtic_Song_Book/

Running

```
$ lilypond -o song_of_the_heather -dbackend=svg song_of_the_heather.ly
```
produces the correct uncropped output. 

(I notice that running `lilypond` from the command line produces a true SVG, whereas the extension  does a base-64 encoding of a PNG, and wraps SVG code around it.)

**Comment by kjcole** [comment]
Any progress?

**Comment by SilverRainZ** [comment]
Sorry, not yet, I will take a look this week.

**Comment by SilverRainZ** [comment]
Cropping an SVG in my environment does not eliminate too much, but also weird:

![火狐截图_2022-07-13T15-03-55 682Z](https://user-images.githubusercontent.com/8090459/178767366-cd93abbe-ce07-436e-93bc-86b0d46e0823.png)

**Comment by kjcole** [comment]
Weird. Yes. Thanks for taking a look. I had hoped that SVG with it's scaling ability would ultimately be a better choice, but the strangeness may force me back to the PNG -- which as previously reported, has its own challenges / bugs...
