### ISSUE TITLE
Configuration change not detected

### ISSUE THREAD

**Issue by Jean-Abou-Samra** [sphinx-notes/lilypond#2]
When changing `lilypond_lilypond_args` and rebuilding, snippets are not rebuilt unless their source has also changed.

**Comment by SilverRainZ** [comment]
Now the whole sphinx environment will be rebuild when configuration changed.

**Comment by SilverRainZ** [comment]
Updated in sphinxnotes-lilypond==1.0

**Comment by Jean-Abou-Samra** [comment]
Thank you!
