### ISSUE TITLE
Audio output does not follow repeat marks

### ISSUE THREAD

**Issue by SilverRainZ** [sphinx-notes/lilypond#22]
Example:

```rst
.. lily::
   :audio:
   :noedge:

   \version "2.22.1"
    
   main = {
     \drums {
       \tempo 4 = 80
       \time 4/4
    
       <<
         {
           \repeat volta 10 { sn8 sn sn8. sn16 }
         }
       >>
     }
   }
    
   \score {
     \main
   }
```

**Comment by tuckerrc** [comment]
You might need to add the `\unfoldRepeats` command to your score ([3.6.6 Using repeats with MIDI](https://lilypond.org/doc/v2.24/Documentation/notation/using-repeats-with-midi))

```
\score {
  \unfoldRepeats {
    \main
  }
}
```

**Comment by SilverRainZ** [comment]
Thank you, I know this. In the past, this extension will automatically insert `\midi{}` block to lilypond source so I will doubt whether to insert `\unfoldRepeats{}` as well, this makes this extension too complex.

For now, we drop this feature in #35, so this is no longer a problem.
