### ISSUE TITLE
No score generated, no "*.music" files to check...

### ISSUE THREAD

**Issue by kjcole** [sphinx-notes/lilypond#3]
**Configuration**

```
Distribution:           Pop!_OS 20.04 LTS (focal)
LilyPond:               2.20.0
Frescobaldi:            3.0.0
Linux kernel:           5.11.0-7633-generic
Python:                 3.8.10
Sphinx:                 4.1.2
sphinxnotes-lilypond:   1.0 
```

I'm just starting with LilyPond. My `.ly` file successfully builds from Frescobaldi, and produces a PDF score and a MIDI file, but when I attempt to include the LilyPond source file in a reStructuredText file, I get:

```
WARNING: failed to generate scores: No score generated, please check "*.music" files under "/tmp/sphinxnotes-lilypondpnhkgqk8"
```

The directory does not contain any `*.music` files but Sphinx did generate the three files `music.ly`, `music.midi` and `music.wav` in that directory. The `music.ly` file looks almost identical to the original file, with:

```
\paper {
    evenFooterMarkup = ##f
    oddFooterMarkup = ##f
}
```

The MIDI and WAV file both play.

inserted at the top (without the indentation). I have attached the two files in question:

* [song_of_the_heather.ly](https://github.com/sphinx-notes/lilypond/files/7118137/song_of_the_heather.ly.txt)
* [song_of_the_heather.rst](https://github.com/sphinx-notes/lilypond/files/7118139/song_of_the_heather.rst.txt)

**Comment by SilverRainZ** [comment]
Hello, I will try to dig into it this weekend.

**Comment by kjcole** [comment]
Removing "`\midi { }`" fixed things. My mistake. I had assumed that your system needed that to generate an audio file.

**Comment by SilverRainZ** [comment]
Add a `\layout {}` also fix this:

```
...
   \midi { }
+  \layout { }
}
```

I think this is not a bug of extension, if you use `\score`, you must specific your output definition,  both `\layout` and `\midi` are output definitions, lilypond may use a empty `\layout {}` when there is not any output definition, so remove `\midi {}` block fixed things.

**Comment by SilverRainZ** [comment]
sphinxnotes-lilypond==1.1 brings HiDPI support, You might be interested :)
