### ISSUE TITLE
Feature request: Option to move audio playback above score

### ISSUE THREAD

**Issue by kjcole** [sphinx-notes/lilypond#4]
When a song has multiple verses printed below the score, rather than embedded in the score, the separation between the beginnng of score and the audio playback bar can be great enough that a reader must scroll up and down to see both. This makes it difficult to start the playback while looking at the beginning of a score. 

An option to place the playback bar above the score would be nice, and I suspect, relatively easy to implement...

**Comment by SilverRainZ** [comment]
Hi @kjcole, I have added a option namedd "controls" for that (see: https://sphinx-notes.github.io/lilypond/#control-bar-at-the-top).

You can build a package byself, or waiting for the release of 1.3

**Comment by kjcole** [comment]
Thank you!  I'll try it out later today.

**Comment by SilverRainZ** [comment]
sphinxnotes-lilypond==1.3 lands this changes.
