### ISSUE TITLE
Question: Can I keep the same scaling between multiple page PNG images?

### ISSUE THREAD

**Issue by kjcole** [sphinx-notes/lilypond#7]
I was using the default paper size A4 in Lilypond but sometimes, if the score is long enough, additional verses without a musical staff are pushed onto a second page. The Sphinx Lilypond extension renders this as two separate PNGs.

Unfortunately, the finished rendering will scale the second PNG so that the text is much larger than in the first PNG.

Is there a way to keep the scale on the second PNG the same as the first?

(I've solved it in one case by changing the Lilypond paper size, but initially, I doubled the page length for one score, and Sphinx blew up with an error about wand cache resources being exhausted or exceeded.  Extending the page length by a smaller amount worked.)

**Comment by SilverRainZ** [comment]
I think you can move more musical score to the second page by using break ling `\break`.

**Comment by kjcole** [comment]
I would like to avoid multiple pages. But if I cannot avoid multiple pages, the height and width of all the pages should be the same, so that no scaling takes place. This would probably require padding the bottom of the last image with enough white space to make the height the same as the first page height.

Adding `\break` statements would only work if I  could compute the best point to avoid scaling on each page. It's possible, but it seems like the wrong solution, I think.

**Comment by SilverRainZ** [comment]
Hi @kjcole, after #31, lilypond can outputs a single PNG whatever how the score is long, which should exactly slove your problem.

**Comment by SilverRainZ** [comment]
for now, you can try the newest alpha version, for example, `sphinxnotes-lilypond==2.0.0a2`, and give a `:noedge:` option.

**Comment by SilverRainZ** [comment]
In stable 2.0.0, this is the default behavior.
